name: rolling_nav_bar
description: A Flutter nav bar with a rolling active indicator behind each icon
version: 0.0.4
homepage: https://github.com/craiglabenz/flutter_rolling_nav_bar

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  badges: ^2.0.2
  flutter_polygon_clipper: ^1.0.4
  tinycolor2: ^2.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
